name: CONTINOUS DEPLOYMENT

on:
  push:
    branches: [ "develop"]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: clean install
        run: mvn clean install

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
      - name: Deploy To Server
        run: |
          echo 'Starting to Deploy...'
          pwd
          scp target/latihancicd-0.0.1-SNAPSHOT.jar ubuntu@${{ secrets.IP }}""
          echo 'Deployment completed successfully'